import Head from 'next/head';
import EntryComponent from '../components/EntryComponent';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hackarena</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <EntryComponent />
    </div>
  );
}
